version: 2
jobs:
  build:
    working_directory: ~/web-branch-deep-linking
    docker:
    - image: circleci/node:6.11.2
    steps:
    - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
    - checkout
    - setup_remote_docker
    - run:
        name: Install Closure compiler
        command: |
            mkdir -p compiler ;
            stat compiler/compiler.jar || (wget http://dl.google.com/closure-compiler/compiler-20170218.zip && unzip -o compiler-20170218.zip -d compiler) ;
    - run:
        name: Install Closure compiler library
        command: |
            mkdir -p compiler/library ;
            stat compiler/library/closure-library-20170218 || (wget https://github.com/google/closure-library/archive/v20170218.zip && unzip -o v20170218.zip -d compiler/library) ;
    - run:
        name: Install Node, Sauce, Phantom, etc.
        command: |
            npm install ;
            sudo npm install -g jsdox ;
            mocha-phantomjs --help || sudo npm install -g mocha-phantomjs ;
            wget https://saucelabs.com/downloads/sc-4.3.13-linux.tar.gz --no-check-certificate ;
            tar -xzf sc-4.3.13-linux.tar.gz ;
            jscs --help || sudo npm install -g jscs ;
            jshint -v || sudo npm install -g jshint ;
            which grunt 2>&1 >/dev/null || sudo npm install -g grunt-cli ;
    - run:
        name: Add Jessie backports PPA
        command: |
            sudo su -c 'echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main" >> /etc/apt/sources.list.d/jessie-backports.list'
    - run:
        name: Add main Jessie PPA
        command: |
            sudo sed -i '/deb http:\/\/deb.debian.org\/debian jessie-updates main/d' /etc/apt/sources.list
    - run:
        name: Install Java
        command: |
            sudo rm -rf /var/lib/apt/lists/*
            sudo apt-get -o Acquire::Check-Valid-Until=false update
            sudo apt install -t jessie-backports openjdk-8-jre-headless ca-certificates-java
    - run:
        name: Install AWS CLI
        command: |
            sudo apt-get install -qq -y python-pip libpython-dev ;
            curl -O https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py ;
            pip install awscli --upgrade --user && echo 'export PATH=/home/circleci/.local/bin:$PATH' >> $BASH_ENV;
            sudo npm install -g slack-cli ;
    - run:
        name: Build minified JS
        command: |
            deployment/test.sh
    - run:
        name: Run deployment script
        command: |
            pip uninstall -y urllib3; pip install urllib3==1.22 --user
            deployment/deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
