# CircleCI configuration file
version: 2.1

jobs:
  # Job one with a unique name
  build:
    docker:
     - image: cimg/base:2022.05
     - image: circleci/node:14.15.0
    working_directory: ~/web-branch-deep-linking
    steps:
      - run:
         name: Set up NPM auth token
         command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - checkout
      - setup_remote_docker
      - run:
          name: Saying Hello
          command: |
            sudo apt update
            sudo apt install openjdk-11-jdk
            sudo update-alternatives --config java
      - run: java -version

  say_hello:
    docker:
     - image: cimg/base:2022.05
     - image: circleci/node:14.15.0
    steps:
      - run: echo "Say hello to YAML!"
      - run:
         name: Set up NPM auth token
         command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - checkout
      - setup_remote_docker
      - run:
          name: Saying Hello
          command: |
            sudo apt update
            sudo apt install openjdk-11-jdk
            sudo update-alternatives --config java
      - run: java -version
  # Job two with a unique name
  say_goodbye:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: echo "Say goodbye to YAML!"

workflows:
  # Name of workflow
  build-and-deploy:
    # List of jobs that will run
    jobs:
      - build